# -*- coding: utf-8 -*-
"""Copy of task 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QjALDtgmnaQsrcBnqCGvjjxH5pkdejIR
"""

import pandas as pd
from google.colab import files

# Upload the file manually
uploaded = files.upload()

# Get the filename (first key in uploaded dict)
file_name = list(uploaded.keys())[0]

# Load the dataset
df = pd.read_csv(file_name)

# Display dataset info
print(df.info())
print(df.head())

# --- 1. Initial Inspection ---
print("Original Dataset Info:")
print(df.info())
print("\nMissing Values:\n", df.isnull().sum())

# --- 2. Remove Duplicates ---
duplicates = df.duplicated().sum()
print(f"\nDuplicate Rows: {duplicates}")
df.drop_duplicates(inplace=True)

# --- 3. Handle Missing Values ---
# For simplicity, fill missing 'director' and 'cast' as 'Unknown'
df['director'].fillna('Unknown', inplace=True)
df['cast'].fillna('Unknown', inplace=True)
df['country'].fillna('Unknown', inplace=True)
df['date_added'] = pd.to_datetime(df['date_added'], errors='coerce')

# --- 4. Standardize Text Columns ---
df['type'] = df['type'].str.strip().str.title()  # Movie / TV Show
df['country'] = df['country'].str.strip()

# --- 5. Rename Columns for Consistency ---
df.columns = df.columns.str.lower().str.replace(' ', '_')

# --- 6. Convert Data Types ---
df['release_year'] = pd.to_numeric(df['release_year'], errors='coerce')
# 'duration' will remain as string; can be split if detailed duration analysis is needed

# --- 7. Final Inspection ---
print("\nCleaned Dataset Info:")
print(df.info())
print("\nPreview:\n", df.head())

# --- 8. Export Cleaned Dataset ---
df.to_csv('cleaned_netflix_data.csv', index=False)
print("\nCleaned dataset saved as 'cleaned_netflix_data.csv'")